# Generated by Django 4.2.4 on 2023-08-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_ourblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourblog',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
