# Generated by Django 4.2.4 on 2023-08-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_ourblog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourblog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
