# Generated by Django 4.2.4 on 2023-08-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_ourblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
