# Generated by Django 4.2.4 on 2023-08-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourservices',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ourservices',
            name='lastName',
        ),
    ]
