# Generated by Django 4.2.4 on 2023-08-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_firstname_ourservices_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
